## Kaggle Competition - House Prices: Advanced Regression Techniques
# Feature Encoding

The main purpose of this section is to individually review each of the columns in the dataset to see if they can be improved for the purposes of linear regression

The code for this module is in: [src/models/FeatureEncoding.py](../src/models/FeatureEncoding.py)

In [18]:
import sys
import os
sys.path.append( os.path.abspath( os.path.join(os.getcwd(), ".." ))) 
from src.utils import reset_root_dir
reset_root_dir()

from cytoolz import groupby
from datetime import datetime
from pandas import DataFrame, Series
from sortedcontainers import SortedDict
import cytoolz
import itertools
import math
import matplotlib
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import pprint
import pydash
import seaborn as sns
import simplejson

from src.utils.Charts import Charts
from src.models import LinearRegressionModel, FeatureEncoding

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 10)

pp = pprint.PrettyPrinter(depth=6)

# Column Categorization and Cleanup

The baseline linear regression model removes non-numeric fields and fills in NaNs with 0

Looking through the individual columns, there are several types of basic feature mapping

Uncorrilated Variables that can be removed
- id: uncorrilated remove

Linear Numeric fields that left unmodified
- LotFrontage: linear numeric
- LotArea: linear numeric
- OverallQual: linear numeric
- OverallCond: linear numeric
- MasVnrArea: linear numeric
- BsmtFinSF2: linear numeric
- BsmtUnfSF: linear numeric
- TotalBsmtSF: linear numeric
- 1stFlrSF: linear numeric
- 2ndFlrSF: linear numeric
- LowQualFinSF: linear numeric
- GrLivArea: linear numeric
- BsmtFullBath: linear numeric
- BsmtHalfBath: linear numeric
- FullBath: linear numeric
- HalfBath: linear numeric
- Bedroom: linear numeric
- Kitchen: linear numeric
- TotRmsAbvGrd: linear numeric
- WoodDeckSF: linear numeric
- OpenPorchSF: linear numeric
- EnclosedPorch: linear numeric
- 3SsnPorch: linear numeric
- ScreenPorch: linear numeric
- PoolArea: linear numeric
- MiscVal: linear numeric
- Fireplaces: linear numeric
- GarageCars: linear numeric
- GarageArea: linear numeric


Absolute Years could be better converted to Ages Relative to current Year
- YearBuilt: numeric - convert to age
- YearRemodAdd: numeric - convert to age
- GarageYrBlt: numeric - convert to age
- YrSold: numeric - convert to age

Month sold is categorical assuming that houe prices have seasons 
- MoSold: categorical

Categorical fields may need OneHotEncoding - https://scikit-learn.org/stable/modules/preprocessing.html
- MSSubClass: categorical
- MSZoning: categorical
- Street: categorical
- Alley: categorical
- LotShape: categorical
- LandContour: categorical
- Utilities: categorical
- LotConfig: categorical
- Neighborhood: categorical
- BldgType: categorical
- HouseStyle: categorical
- RoofStyle: categorical
- RoofMatl: categorical
- MasVnrType: categorical
- Foundation: categorical
- BsmtExposure: categorical
- Heating: categorical
- Functional: categorical | categorical to numeric
- GarageFinish: categorical | categorical to numeric
- Fence: categorical | categorical to numeric
- SaleType: categorical
- SaleCondition: categorical
- MiscFeature: categorical
- Electrical: categorical
- GarageType: categorical
- PavedDrive: (Yes / Partial / No )

Categorical fields with optional multiple values
- Condition1 + Condition2: multiple categorical
- Exterior1st + Exterior2nd: multiple categorical
- BsmtFinType1 + BsmtFinType2: multiple categorical

LabelEncoder Quality Categories: Ex:Excellent, Gd:Good, TA:Average/Typical, Fa:Fair, Po:Poor, NA
- ExterQual: categorical to numeric
- ExterCond: categorical to numeric
- BsmtQual: categorical to numeric
- BsmtCond: categorical to numeric
- HeatingQC: categorical to numeric
- KitchenQual: categorical to numeric
- FireplaceQu: categorical to numeric
- GarageQual: categorical to numeric
- GarageCond: categorical to numeric
- PoolQC: categorical to numeric

Boolean fields are Y or N which can converted to numeric
- CentralAir: boolean




In [2]:
LinearRegressionModel().data['X_test']

Id  MSSubClass  LotFrontage  LotArea  OverallQual  OverallCond  \
0     1461          20         80.0    11622            5            6   
1     1462          20         81.0    14267            6            6   
2     1463          60         74.0    13830            5            5   
3     1464          60         78.0     9978            6            6   
4     1465         120         43.0     5005            8            5   
...    ...         ...          ...      ...          ...          ...   
1454  2915         160         21.0     1936            4            7   
1455  2916         160         21.0     1894            4            5   
1456  2917          20        160.0    20000            5            7   
1457  2918          85         62.0    10441            5            5   
1458  2919          60         74.0     9627            7            5   

      YearBuilt  YearRemodAdd  MasVnrArea  BsmtFinSF1  BsmtFinSF2  BsmtUnfSF  \
0          1961          1961         0.0       468.0       144.0      270.0   
1          1958          1958       108.0       923.0         0.0      406.0   
2          1997          1998         0.0       791.0         0.0      137.0   
3          1998          1998        20.0       602.0         0.0      324.0   
4          1992          1992         0.0       263.0         0.0     1017.0   
...         ...           ...         ...         ...         ...        ...   
1454       1970          1970         0.0         0.0         0.0      546.0   
1455       1970          1970         0.0       252.0         0.0      294.0   
1456       1960          1996         0.0      1224.0         0.0        0.0   
1457       1992          1992         0.0       337.0         0.0      575.0   
1458       1993          1994        94.0       758.0         0.0      238.0   

      TotalBsmtSF  1stFlrSF  2ndFlrSF  LowQualFinSF  GrLivArea  BsmtFullBath  \
0           882.0       896         0             0        896           0.0   
1          1329.0      1329         0             0       1329           0.0   
2           928.0       928       701             0       1629           0.0   
3           926.0       926       678             0       1604           0.0   
4          1280.0      1280         0             0       1280           0.0   
...           ...       ...       ...           ...        ...           ...   
1454        546.0       546       546             0       1092           0.0   
1455        546.0       546       546             0       1092           0.0   
1456       1224.0      1224         0             0       1224           1.0   
1457        912.0       970         0             0        970           0.0   
1458        996.0       996      1004             0       2000           0.0   

      BsmtHalfBath  FullBath  HalfBath  BedroomAbvGr  KitchenAbvGr  \
0              0.0         1         0             2             1   
1              0.0         1         1             3             1   
2              0.0         2         1             3             1   
3              0.0         2         1             3             1   
4              0.0         2         0             2             1   
...            ...       ...       ...           ...           ...   
1454           0.0         1         1             3             1   
1455           0.0         1         1             3             1   
1456           0.0         1         0             4             1   
1457           1.0         1         0             3             1   
1458           0.0         2         1             3             1   

      TotRmsAbvGrd  Fireplaces  GarageYrBlt  GarageCars  GarageArea  \
0                5           0       1961.0         1.0       730.0   
1                6           0       1958.0         1.0       312.0   
2                6           1       1997.0         2.0       482.0   
3                7           1       1998.0         2.0       470.0   
4

After feature encoding, we have gone from 37 features to 254 features

In [3]:
FeatureEncoding().data['X_test']

Id  LotFrontage  LotArea  OverallQual  OverallCond  YearBuilt  \
0     1461         80.0    11622            5            6       1961   
1     1462         81.0    14267            6            6       1958   
2     1463         74.0    13830            5            5       1997   
3     1464         78.0     9978            6            6       1998   
4     1465         43.0     5005            8            5       1992   
...    ...          ...      ...          ...          ...        ...   
1454  2915         21.0     1936            4            7       1970   
1455  2916         21.0     1894            4            5       1970   
1456  2917        160.0    20000            5            7       1960   
1457  2918         62.0    10441            5            5       1992   
1458  2919         74.0     9627            7            5       1993   

      YearRemodAdd  MasVnrArea  BsmtFinSF1  BsmtFinSF2  BsmtUnfSF  \
0             1961         0.0       468.0       144.0      270.0   
1             1958       108.0       923.0         0.0      406.0   
2             1998         0.0       791.0         0.0      137.0   
3             1998        20.0       602.0         0.0      324.0   
4             1992         0.0       263.0         0.0     1017.0   
...            ...         ...         ...         ...        ...   
1454          1970         0.0         0.0         0.0      546.0   
1455          1970         0.0       252.0         0.0      294.0   
1456          1996         0.0      1224.0         0.0        0.0   
1457          1992         0.0       337.0         0.0      575.0   
1458          1994        94.0       758.0         0.0      238.0   

      TotalBsmtSF  1stFlrSF  2ndFlrSF  LowQualFinSF  GrLivArea  BsmtFullBath  \
0           882.0       896         0             0        896           0.0   
1          1329.0      1329         0             0       1329           0.0   
2           928.0       928       701             0       1629           0.0   
3           926.0       926       678             0       1604           0.0   
4          1280.0      1280         0             0       1280           0.0   
...           ...       ...       ...           ...        ...           ...   
1454        546.0       546       546             0       1092           0.0   
1455        546.0       546       546             0       1092           0.0   
1456       1224.0      1224         0             0       1224           1.0   
1457        912.0       970         0             0        970           0.0   
1458        996.0       996      1004             0       2000           0.0   

      BsmtHalfBath  FullBath  HalfBath  BedroomAbvGr  KitchenAbvGr  \
0              0.0         1         0             2             1   
1              0.0         1         1             3             1   
2              0.0         2         1             3             1   
3              0.0         2         1             3             1   
4              0.0         2         0             2             1   
...            ...       ...       ...           ...           ...   
1454           0.0         1         1             3             1   
1455           0.0         1         1             3             1   
1456           0.0         1         0             4             1   
1457           1.0         1         0             3             1   
1458           0.0         2         1             3             1   

      TotRmsAbvGrd  Fireplaces  GarageYrBlt  GarageCars  GarageArea  \
0                5           0       1961.0         1.0       730.0   
1                6           0       1958.0         1.0       312.0   
2                6           1       1997.0         2.0       482.0   
3                7           1       1998.0         2.0       470.0   
4                5           0       1992.0         2.0       506.0   
...            ...         ...          ...         ...         ...   
145

# Scoring

We can test each of the feature encodings indivudally as well as compare against a baseline 

Findings:
- (0.1978) X_feature_exclude      - strange corrilation between id and price??? = remove id on therotical grounds
- (0.1946) X_feature_year_ages    - minor reduction in score encoding relative ages = leave absolute year as feature
- (0.1942) none                   - baseline linear regression score
- (0.1855) X_feature_label_encode - significant improvement over baseline score
- (0.1829) X_feature_onehot       - significant improvement over baseline score - better than X_feature_label_encode
- (0.1823) all features           - combining all features doesn't get much better than X_feature_onehot alone

In [4]:
results = FeatureEncoding.feature_scores([ "X_feature_exclude", "X_feature_year_ages", "X_feature_label_encode", "X_feature_onehot" ], depth=1)
for result in reversed(results): print( result )

(0.1978, 'FeatureEncoding', 'LinearRegression', 'X_feature_exclude')
(0.1946, 'FeatureEncoding', 'LinearRegression', 'X_feature_year_ages')
(0.1942, 'FeatureEncoding', 'LinearRegression', '')
(0.1855, 'FeatureEncoding', 'LinearRegression', 'X_feature_label_encode')
(0.1829, 'FeatureEncoding', 'LinearRegression', 'X_feature_onehot')
(0.1823, 'FeatureEncoding', 'LinearRegression', 'X_feature_exclude X_feature_year_ages X_feature_label_encode X_feature_onehot')


### Submit to Kaggle
https://www.kaggle.com/c/house-prices-advanced-regression-techniques/submissions

```
$ kaggle competitions submit -c house-prices-advanced-regression-techniques -f data/submissions/FeatureEncoding.csv -m "FeatureEncoding.py - label + onehot encoding"
```
    
- Your submission scored 0.80406, which is not an improvement of your best score (0.20892). Keep trying!
- Kaggle Rank 3778 / 4375


Whilst FeatureEncoding is theoretically valid and improves the local score, it results in a major downgrade of the Kaggle score

# Polynomial Features

sklearn.preprocessing.PolynomialFeatures() massively expands the number of features, multiplying each column by every other column, including itself.

We have thus gone from 37 features to 1039 features (almost the same size as dataset rows)

In [5]:
model = FeatureEncoding(features=[ "X_feature_exclude", "X_feature_year_ages", "X_feature_label_encode", "X_feature_onehot", "X_feature_polynomial" ])
(  
    LinearRegressionModel().data['X_train'].shape,
    model.data['X_train'].shape,
)

((1095, 37), (1095, 1039))

This also has a major detremental effect on the score 0.1942 -> 0.6264

In [6]:
results = FeatureEncoding.feature_scores([ "X_feature_exclude", "X_feature_year_ages", "X_feature_label_encode", "X_feature_onehot", "X_feature_polynomial" ], depth=1)
for result in reversed(results): print( result )

(0.6264, 'FeatureEncoding', 'LinearRegression', 'X_feature_polynomial')
(0.4039, 'FeatureEncoding', 'LinearRegression', 'X_feature_exclude X_feature_year_ages X_feature_label_encode X_feature_onehot X_feature_polynomial')
(0.1978, 'FeatureEncoding', 'LinearRegression', 'X_feature_exclude')
(0.1946, 'FeatureEncoding', 'LinearRegression', 'X_feature_year_ages')
(0.1942, 'FeatureEncoding', 'LinearRegression', '')
(0.1855, 'FeatureEncoding', 'LinearRegression', 'X_feature_label_encode')
(0.1829, 'FeatureEncoding', 'LinearRegression', 'X_feature_onehot')


In [16]:
Series(model.predict()['LinearRegression']).describe()

count    1.459000e+03
mean     2.848032e+05
std      1.507450e+06
min     -4.711940e+06
25%      1.172821e+05
50%      1.856476e+05
75%      2.697611e+05
max      5.444014e+07
dtype: float64

### Hypothesis 
We now have far too many features and are overfitting the data with lots of uncorreleated features. Our polynomial model is also predicting negative prices for some houses.

Now that we have completly trashed our score, it can only get better from here

TODO: Investigate - Regularization: Ridge, Lasso and Elastic Net 

### Submit to Kaggle
```
$ kaggle competitions submit -c house-prices-advanced-regression-techniques -f data/submissions/PolynomialFeatureEncoding.csv -m "FeatureEncoding.py - 1039 Polynomial Features"
```
    
- Your submission scored 2.87097, which is not an improvement of your best score (0.20892). Keep trying!
- Kaggle Rank 3861 / 4486


